on:
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: node build.js
      - run: cp package.json build/package.json
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.OAUTH_TOKEN }}
          function_id: ${{ secrets.FUNCTION_ID }}
          runtime: 'nodejs16'
          memory: '128'
          entrypoint: 'index.handler'
          service_account: ${{ secrets.SERVICE_ACCOUNT_ID }}
          environment: SECRET_KEY=${{ secrets.SECRET_KEY }}},DATABASE=${{ secrets.DATABASE }},HOST=https://gatsby-test-nuk.pages.dev
          source: './build/'
